# This is a basic workflow to help you get started with Actions

name: produto-api-cicd

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build and push Docker images  
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./produtos-api/src
          file: ./produtos-api/src/Dockerfile
          push: true
          tags: |
            rodriggoarantes/produto-api:latest
            rodriggoarantes/produto-api:${{github.run_number}}
      

