# This is a basic workflow to help you get started with Actions

name: produto-api-cicd

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker images  
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./produtos-api
          file: ./produtos-api/Dockerfile
          push: true
          tags: |
            rodriggoarantes/produto-api:latest
            rodriggoarantes/produto-api:${{github.run_number}}
      


  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.DIGINALOCEAN_K8S_CONFIG}}

      - name: Deploy MongoDB to Kubernetes
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            ./produtos-api/k8s/db/deployment.yaml
            ./produtos-api/k8s/db/service.yaml
          
